/**
 * Dutch word list.
 *
 * Written natively for a Dutch/Flemish table: bikes, weather complaints,
 * borrel culture and the small rituals everyone recognises.
 */
export const dutchWords: string[] = [
  // Eten en drinken
  'Stroopwafel',
  'Bitterbal',
  'Hagelslag',
  'Patat met',
  'Frikandel',
  'Oliebollen',
  'Kaasplankje',
  'Pannenkoek',
  'Haring happen',
  'Drop',
  'Poffertjes',
  'Erwtensoep',
  'Boterham',
  'Speculaas',
  'Appeltaart',
  'Broodje kroket',

  // Typisch
  'Gezellig',
  'Borrel',
  'Klompen',
  'Molen',
  'Tulpen',
  'Polder',
  'Dijk',
  'Grachten',
  'Oranje',
  'Koningsdag',
  'Sinterklaas',
  'Verjaardagskalender',
  'Kringverjaardag',
  'Agenda prikken',
  'Tikkie sturen',
  'Zuinig',

  // Vervoer
  'Fiets',
  'Bakfiets',
  'Fietsbel',
  'Lekke band',
  'Treinvertraging',
  'OV-chipkaart',
  'Scooter',
  'Veerpont',
  'File',
  'Rotonde',
  'Fietsenstalling',
  'Brommer',

  // Weer
  'Tegenwind',
  'Motregen',
  'Hagelbui',
  'Storm',
  'Mist',
  'Eerste zonnestraal',
  'Hittegolf',
  'Gladheid',
  'Regenboog',
  'Onweer',

  // Mensen
  'Buurman',
  'Schoonmoeder',
  'Tandarts',
  'Scheidsrechter',
  'Kapper',
  'Postbode',
  'Boer',
  'Loodgieter',
  'Oppas',
  'Goochelaar',
  'Badmeester',
  'Influencer',

  // Dieren
  'Koe',
  'Egel',
  'Pinguïn',
  'Eekhoorn',
  'Meeuw',
  'Konijn',
  'Schaap',
  'Zeehond',
  'Vleermuis',
  'Kwal',
  'Hamster',
  'Ooievaar',

  // Plekken
  'Vuurtoren',
  'Zolder',
  'Camping',
  'Pretpark',
  'Museum',
  'Sauna',
  'Strandtent',
  'Wasserette',
  'Dierentuin',
  'Achtbaan',
  'Bouwmarkt',
  'Kinderboerderij',
  'Zwembad',
  'Terras',

  // Situaties
  'Kater',
  'Jetlag',
  'Hik',
  'Niezen',
  'Snurken',
  'Kriebel in je neus',
  'Sleutels kwijt',
  'Verslapen',
  'In de rij staan',
  'Inparkeren',
  'Cadeau inpakken',
  'Blind date',
  'Sollicitatiegesprek',
  'Verhuizen',
  'Zwemles',
  'Rijexamen',

  // Gevoelens
  'Heimwee',
  'Plankenkoorts',
  'Kippenvel',
  'Vlinders in je buik',
  'Zonnebrand',
  'Slaapbeen',
  'Déjà vu',
  'Faalangst',
  'Voorpret',
  'Uitslaapdag',

  // Sport en hobby
  'Schaatsen',
  'Elfstedentocht',
  'Voetbal',
  'Hockey',
  'Korfbal',
  'Wielrennen',
  'Yoga',
  'Karate',
  'Zeilen',
  'Darten',
  'Schaken',
  'Verstoppertje',
  'Karaoke',
  'Breien',
  'Tuinieren',
  'Marathon',

  // Techniek en nu
  'Selfie',
  'Podcast',
  'Emoji',
  'Wifi-wachtwoord',
  'Groepsapp',
  'Batterij bijna leeg',
  'Screenshot',
  'Videobellen',
  'Spam',
  'Vliegtuigmodus',
  'QR-code',
  'Streamen',

  // Dingen
  'Paraplu',
  'Wekker',
  'Koffer',
  'Zonnebril',
  'Kauwgom',
  'Afstandsbediening',
  'Stofzuiger',
  'Tandenborstel',
  'Spaarpot',
  'Kruiwagen',
  'Waterkoker',
  'Trampoline',
  'Bubbeltjesplastic',
  'Ladder',
  'Vuurwerk',
  'Zandkasteel',
  'Snor',
  'Tattoo',
  'Schatkaart',
  'Tijdmachine',
];
