/**
 * English word list.
 *
 * Design rules for every list in this folder (see ./README.md):
 *  - Words must be describable in a few seconds by gesture, synonym or association.
 *  - Prefer evocative, visual or funny over flat and generic ("Hangover" beats "Apple").
 *  - Spread across categories: people, places, objects, food, actions, pop culture,
 *    feelings, sport, tech, seasonal.
 *  - Never abstract grammar words (prepositions, pronouns) — they cannot be acted out.
 *  - Keep it family-friendly and non-political.
 */
export const englishWords: string[] = [
  // People & roles
  'Astronaut',
  'Detective',
  'Dentist',
  'Lifeguard',
  'Referee',
  'Magician',
  'Babysitter',
  'Barber',
  'Firefighter',
  'Influencer',
  'Bodyguard',
  'Tour guide',
  'Plumber',
  'Clown',
  'Librarian',

  // Characters & creatures
  'Zombie',
  'Pirate',
  'Vampire',
  'Mermaid',
  'Superhero',
  'Dinosaur',
  'Unicorn',
  'Ghost',
  'Penguin',
  'Octopus',
  'Sloth',
  'Flamingo',
  'Hedgehog',
  'Werewolf',

  // Food & drink
  'Spaghetti',
  'Barbecue',
  'Popcorn',
  'Pancake',
  'Avocado',
  'Chocolate',
  'Sushi',
  'Ice cream',
  'Pizza slice',
  'Hot sauce',
  'Cereal',
  'Leftovers',
  'Birthday cake',
  'Coffee run',
  'Garlic',

  // Everyday objects
  'Umbrella',
  'Shopping trolley',
  'Alarm clock',
  'Bubble wrap',
  'Suitcase',
  'Sunglasses',
  'Chewing gum',
  'Remote control',
  'Vacuum cleaner',
  'Toothbrush',
  'Piggy bank',
  'Mousetrap',
  'Wheelbarrow',
  'Kettle',
  'Trampoline',

  // Actions & situations
  'Sneeze',
  'Snoring',
  'Hiccups',
  'Tripping over',
  'Whistling',
  'Juggling',
  'Tickling',
  'Yawning',
  'Blushing',
  'Eavesdropping',
  'Queueing',
  'Oversleeping',
  'Parallel parking',
  'Wrapping a present',
  'Losing your keys',

  // Feelings & states
  'Hangover',
  'Jet lag',
  'Homesick',
  'Stage fright',
  'Butterflies',
  'Brain freeze',
  'Deja vu',
  'Goosebumps',
  'Sunburn',
  'Pins and needles',
  'Cold feet',
  'Food coma',

  // Places
  'Airport',
  'Lighthouse',
  'Volcano',
  'Desert island',
  'Haunted house',
  'Rooftop',
  'Waterfall',
  'Campsite',
  'Museum',
  'Launderette',
  'Rollercoaster',
  'Treehouse',
  'Greenhouse',
  'Car wash',

  // Events & occasions
  'Wedding',
  'Honeymoon',
  'Sleepover',
  'Road trip',
  'Job interview',
  'Surprise party',
  'Graduation',
  'Fire drill',
  'Blind date',
  'Camping trip',
  'Talent show',
  'Housewarming',

  // Sport & hobbies
  'Karate',
  'Yoga',
  'Marathon',
  'Skateboard',
  'Bungee jump',
  'Snorkelling',
  'Chess',
  'Karaoke',
  'Gardening',
  'Knitting',
  'Surfing',
  'Ice skating',
  'Darts',
  'Hide and seek',

  // Tech & modern life
  'Selfie',
  'Podcast',
  'Emoji',
  'Wi-Fi password',
  'Group chat',
  'Battery low',
  'Spam email',
  'Video call',
  'Screenshot',
  'Autocorrect',
  'Streaming',
  'Airplane mode',
  'QR code',
  'Smartwatch',

  // Weather & nature
  'Lightning',
  'Tornado',
  'Rainbow',
  'Snowman',
  'Heatwave',
  'Quicksand',
  'Full moon',
  'Shooting star',
  'Puddle',
  'Fog',

  // Bits of fun
  'Moustache',
  'Fireworks',
  'Sandcastle',
  'Balloon',
  'Confetti',
  'Piñata',
  'Bubble bath',
  'Tattoo',
  'Time machine',
  'Treasure map',
  'Secret handshake',
  'Paper aeroplane',
  'Snow globe',
  'Kaleidoscope',
];
