/**
 * French word list.
 *
 * Written natively: apéro, la grève, la rentrée and the small daily rituals
 * a French-speaking table recognises without explanation.
 */
export const frenchWords: string[] = [
  // Nourriture et boisson
  'Baguette',
  'Croissant',
  'Fromage qui pue',
  'Escargots',
  'Ratatouille',
  'Crêpe',
  'Macaron',
  'Quiche',
  'Tarte tatin',
  'Pain au chocolat',
  'Raclette',
  'Bouillabaisse',
  'Steak frites',
  'Éclair au chocolat',
  'Cornichon',
  'Apéro',
  'Pique-nique',
  'Madeleine',

  // Culture et vie quotidienne
  'La bise',
  'La grève',
  'La rentrée',
  'Terrasse de café',
  'Marché du dimanche',
  'Bricolage',
  'Pétanque',
  'Brocante',
  'Fête de la musique',
  'Quatorze juillet',
  'Galette des rois',
  'Réveillon',
  'Vacances d’été',
  'Carnaval',

  // Personnes
  'Boulanger',
  'Dentiste',
  'Arbitre',
  'Coiffeur',
  'Pompier',
  'Facteur',
  'Plombier',
  'Voisin curieux',
  'Baby-sitter',
  'Magicien',
  'Maître nageur',
  'Guide touristique',
  'Clown',
  'Grand-mère',

  // Animaux
  'Pingouin',
  'Pieuvre',
  'Paresseux',
  'Flamant rose',
  'Hérisson',
  'Chauve-souris',
  'Écureuil',
  'Mouette',
  'Baleine',
  'Papillon',
  'Fourmi',
  'Coccinelle',
  'Renard',
  'Sanglier',

  // Lieux
  'Phare',
  'Volcan',
  'Île déserte',
  'Maison hantée',
  'Toit',
  'Cascade',
  'Camping',
  'Musée',
  'Laverie',
  'Montagnes russes',
  'Grenier',
  'Plage',
  'Désert',
  'Château',
  'Métro',

  // Situations
  'Gueule de bois',
  'Décalage horaire',
  'Hoquet',
  'Éternuement',
  'Ronflement',
  'Perdre ses clés',
  'Se réveiller en retard',
  'Faire la queue',
  'Créneau',
  'Emballer un cadeau',
  'Rendez-vous surprise',
  'Entretien d’embauche',
  'Déménagement',
  'Permis de conduire',
  'Fête surprise',
  'Panne d’ascenseur',

  // Sensations
  'Nostalgie',
  'Mal du pays',
  'Chair de poule',
  'Papillons dans le ventre',
  'Coup de soleil',
  'Jambe engourdie',
  'Déjà-vu',
  'Trac',
  'Fou rire',
  'Envie de sucré',

  // Sport et loisirs
  'Football',
  'Marathon',
  'Yoga',
  'Karaté',
  'Surf',
  'Plongée',
  'Échecs',
  'Karaoké',
  'Jardinage',
  'Tricot',
  'Patinage',
  'Fléchettes',
  'Cache-cache',
  'Cyclisme',
  'Escalade',

  // Technologie
  'Selfie',
  'Podcast',
  'Émoji',
  'Mot de passe wifi',
  'Groupe WhatsApp',
  'Batterie faible',
  'Capture d’écran',
  'Appel vidéo',
  'Spam',
  'Mode avion',
  'Code QR',
  'Correcteur automatique',

  // Météo et nature
  'Éclair',
  'Tornade',
  'Arc-en-ciel',
  'Bonhomme de neige',
  'Canicule',
  'Sables mouvants',
  'Pleine lune',
  'Étoile filante',
  'Flaque',
  'Brouillard',

  // Objets
  'Parapluie',
  'Réveil',
  'Valise',
  'Lunettes de soleil',
  'Chewing-gum',
  'Télécommande',
  'Aspirateur',
  'Brosse à dents',
  'Tirelire',
  'Brouette',
  'Bouilloire',
  'Trampoline',
  'Papier bulle',
  'Échelle',
  'Feux d’artifice',
  'Château de sable',
  'Moustache',
  'Tatouage',
  'Carte au trésor',
  'Machine à remonter le temps',
];
