/**
 * Maltese word list.
 *
 * Written natively rather than translated from English: the fun of a local deck
 * comes from things everyone at a Maltese table recognises instantly (festa,
 * pastizzi, ir-riħ tal-Majjistral) rather than generic nouns.
 */
export const malteseWords: string[] = [
  // Ikel u xorb
  'Pastizz',
  'Ftira',
  'Imqaret',
  'Ġbejna',
  'Bragioli',
  'Fenkata',
  'Kusksu',
  'Qagħaq tal-għasel',
  'Bigilla',
  'Aljotta',
  'Timpana',
  'Ross il-forn',
  'Hobż biż-żejt',
  'Kannoli',
  'Figolla',
  'Bajtra tax-xewk',
  'Żeppoli',
  'Helwa tat-Tork',

  // Festi u tradizzjonijiet
  'Festa',
  'Logħob tan-nar',
  'Marċ ta’ filgħodu',
  'Bandalora',
  'Karnival',
  'Mnarja',
  'Purcissjoni',
  'Banda',
  'Ġostra',
  'Presepju',
  'Quccija',
  'Lejlet il-festa',

  // Postijiet
  'Mdina',
  'Il-Belt',
  'Ċirkewwa',
  'Blue Lagoon',
  'Ġgantija',
  'Ħaġar Qim',
  'Għar Dalam',
  'Popeye Village',
  'Marsaxlokk',
  'Il-Fosos',
  'Sqaq',
  'Bieb il-Belt',
  'Pjazza',
  'Każin',
  'Ċimiterju',
  'Suq',

  // Trasport
  'Karozzin',
  'Luzzu',
  'Vapur t’Għawdex',
  'Xarabank',
  'Traffiku',
  'Roundabout',
  'Mutur',
  'Dgħajsa tal-pass',
  'Pont',
  'Parkeġġ',

  // Nies
  'Sajjied',
  'Bennej',
  'Qassis',
  'Tabib',
  'Għalliem',
  'Pulizija',
  'Furnar',
  'Bidwi',
  'Kantant',
  'Sewwieq',
  'Ġar kurjuż',
  'Nanna',

  // Annimali
  'Fenek',
  'Qattus',
  'Kelb',
  'Delfin',
  'Ħanżir',
  'Għasfur',
  'Gremxula',
  'Żrinġ',
  'Baqra',
  'Nemla',
  'Naħla',
  'Farfett',
  'Bukkett',
  'Qanfud',

  // Natura u temp
  'Xemx tisreġ',
  'Majjistral',
  'Xlokk',
  'Qawsalla',
  'Ragħad',
  'Beraq',
  'Sajf',
  'Xita qawwija',
  'Baħar qawwi',
  'Irdum',
  'Għar',
  'Gżira',
  'Widien',
  'Siġra taż-żebbuġ',
  'Ħarifa',

  // Fid-dar
  'Bejt',
  'Gallarija',
  'Ċavetta',
  'Mejda',
  'Siġġu',
  'Friġġ',
  'Banju',
  'Mera',
  'Tapit',
  'Kutra',
  'Xemgħa',
  'Kċina',
  'Ħasil',
  'Bieb',

  // Azzjonijiet u sitwazzjonijiet
  'Tgħawwem',
  'Tiżfen',
  'Tagħtas',
  'Tonghos',
  'Titkellem ħafna',
  'Tinsa l-isem',
  'Tirbaħ il-lotterija',
  'Tidħak bil-qalb',
  'Tistenna fil-kju',
  'Tinqabad fix-xita',
  'Titlef iċ-ċavetta',
  'Tqum tard',
  'Taqbeż il-ħajt',
  'Iċċempel lil ommok',

  // Ħajja moderna
  'Selfie',
  'Wi-Fi',
  'Mowbajl bla batterija',
  'Grupp tal-WhatsApp',
  'Televixin',
  'Kompjuter',
  'Kamera',
  'Drone',
  'Eurovision',
  'Podcast',
  'Screenshot',

  // Sport u passatempi
  'Futbol',
  'Waterpolo',
  'Boċċi',
  'Għawm',
  'Tiġrija taż-żwiemel',
  'Bocci fuq il-plajja',
  'Snorkelling',
  'Ċess',
  'Karaoke',
  'Kant',
  'Kitarra',
  'Pjanu',
  'Bandli',
  'Logħob tal-karti',

  // Sensazzjonijiet
  'Nostalġija',
  'Sogħba',
  'Ferħ',
  'Biża',
  'Ghajjien',
  'Sorpriża',
  'Skuma',
  'Mistħija',
  'Nervi',
  'Ħeġġa',

  // Oġġetti u affarijiet
  'Umbrella',
  'Nuċċali tax-xemx',
  'Bagalja',
  'Arloġġ',
  'Flus',
  'Ktieb',
  'Ritratt',
  'Ħabel',
  'Xkupa',
  'Musmar',
  'Pinzell',
  'Sptar',
  'Skola',
  'Knisja',
  'Bandiera',
  'Għonnella',
];
