/**
 * Maltese word list.
 *
 * Two halves:
 *  - Things everyone at a Maltese table recognises instantly (festa,
 *    pastizzi, il-Majjistral, it-traffiku), written natively.
 *  - Internationally famous people, places, films and brands, the same kind
 *    the English and Dutch decks carry. Places use their Maltese names
 *    (It-Torri Eiffel, Il-Kolossew); brands keep their own.
 *
 * Plain everyday nouns (riħ, kelb, mejda, ktieb) are deliberately left out:
 * they are too easy to describe and too dull to guess.
 */
export const malteseWords: string[] = [
  // Ikel u xorb
  'Pastizz',
  'Pastizzerija',
  'Ftira',
  'Imqaret',
  'Ġbejna',
  'Bragioli',
  'Fenkata',
  'Stuffat tal-fenek',
  'Kusksu',
  'Qagħaq tal-għasel',
  'Qubbajt',
  'Bigilla',
  'Aljotta',
  'Timpana',
  'Ross il-forn',
  'Ħobż biż-żejt',
  'Torta tal-lampuki',
  'Kannoli',
  'Figolla',
  'Bajtra tax-xewk',
  'Żeppoli',
  'Ħelwa tat-Tork',
  'Kinnie',
  'Twistees',

  // Festi u tradizzjonijiet
  'Festa',
  'Logħob tan-nar',
  'Marċ ta’ filgħodu',
  'Bandalora',
  'Karnival',
  'Mnarja',
  'Purċissjoni',
  'Banda',
  'Presepju',
  'Quċċija',
  'Lejlet il-festa',
  'Każin tal-banda',
  'Għonnella',

  // Postijiet f'Malta
  'Mdina',
  'Il-Belt Valletta',
  'Ċirkewwa',
  'Blue Lagoon',
  'Kemmuna',
  'Ġgantija',
  'Ħaġar Qim',
  'Għar Dalam',
  'Popeye Village',
  'Marsaxlokk',
  'Paceville',
  'Tas-Sliema',
  'Il-Fosos',
  'Bieb il-Belt',
  'Il-Fontana tat-Tritoni',
  'Sqaq',

  // Trasport u ħajja ta' kuljum
  'Karozzin',
  'Luzzu',
  'Dgħajsa tal-pass',
  'Vapur t’Għawdex',
  'Xarabank',
  'Traffiku',
  'Roundabout',
  'Parkeġġ',
  'Bolt',
  'Ryanair',
  'Ġar kurjuż',
  'Nanna',
  'Gallarija',
  'Bejt',

  // Nies
  'Sajjied',
  'Bennej',
  'Furnar',
  'Qassis',
  'Surmast tal-banda',
  'Tal-ħaxix',

  // Annimali
  'Fenek',
  'Gremxula',
  'Qanfud',
  'Delfin',
  'Qarnita',
  'Ħuta tal-Lampuki',
  'Pappagall',
  'Iljunfant',
  'Pingwin',
  'Kanguru',
  'Żebra',
  'Ġiraffa',
  'Dinosawru',

  // Natura u temp
  'Majjistral',
  'Xlokk',
  'Qawsalla',
  'Nżul ix-xemx',
  'Xita qawwija',
  'Baħar qawwi',
  'Irdum',
  'Siġra taż-żebbuġ',
  'Sħana tal-Awwissu',
  'Ħarifa',

  // Azzjonijiet u sitwazzjonijiet
  'Tgħawwem',
  'Tiżfen',
  'Tagħtas',
  'Tongħos',
  'Titkellem ħafna',
  'Tinsa l-isem',
  'Tirbaħ il-lotterija',
  'Tidħak bil-qalb',
  'Tistenna fil-kju',
  'Tinqabad fix-xita',
  'Titlef iċ-ċavetta',
  'Tqum tard',
  'Iċċempel lil ommok',
  'Tfittex parkeġġ',
  'Tieħu selfie',

  // Ħajja moderna
  'Selfie',
  'Wi-Fi',
  'Mowbajl bla batterija',
  'Grupp tal-WhatsApp',
  'Drone',
  'Podcast',
  'Screenshot',

  // Sport u passatempi
  'Futbol',
  'Waterpolo',
  'Boċċi',
  'Tiġrija taż-żwiemel',
  'Snorkelling',
  'Karaoke',
  'Bandli',
  'Logħob tal-karti',
  'Tombla',

  // Sensazzjonijiet
  'Nostalġija',
  'Mistħija',

  // Oġġetti
  'Nuċċali tax-xemx',
  'Bagalja',
  'Kitarra elettrika',

  // Postijiet famużi fid-dinja
  'It-Torri Eiffel',
  'Il-Kolossew',
  'Il-Ħajt taċ-Ċina',
  'Il-Piramidi',
  'L-Istatwa tal-Libertà',
  'Big Ben',
  'It-Taj Mahal',
  'Mount Everest',
  'Il-Vatikan',
  'Venezja',
  'Ruma',
  'Pariġi',
  'Londra',
  'New York',
  'Sqallija',
  'L-Etna',
  'Hollywood',
  'Las Vegas',
  'Dubai',
  'Disneyland',
  'Il-Polu tat-Tramuntana',
  'Is-Saħara',

  // Nies famużi
  'Messi',
  'Cristiano Ronaldo',
  'Michael Jackson',
  'Beyoncé',
  'Taylor Swift',
  'Lady Gaga',
  'Elvis Presley',
  'Einstein',
  'Leonardo da Vinci',
  'Shakespeare',
  'Napuljun',
  'Kleopatra',
  'Il-Papa',
  'Mr Bean',
  'Santa Klaws',

  // Films u karattri
  'Harry Potter',
  'Titanic',
  'Star Wars',
  'Game of Thrones',
  'Gladiator',
  'Frozen',
  'Shrek',
  'Spider-Man',
  'Superman',
  'Batman',
  'Mickey Mouse',
  'Barbie',
  'Pinokkjo',
  'Is-Sirena ċkejkna',
  'James Bond',
  'Il-Mona Lisa',

  // Marki u teknoloġija
  'Apple',
  'iPhone',
  'Netflix',
  'McDonald’s',
  'Coca-Cola',
  'Nutella',
  'Lego',
  'IKEA',
  'Instagram',
  'TikTok',
  'YouTube',
  'Google',
  'PlayStation',
  'Pokémon',

  // Sport internazzjonali
  'Il-Formula 1',
  'Champions League',
  'Il-Logħob Olimpiku',
  'Juventus',
  'Manchester United',
  'Real Madrid',
  'Eurovision',
];
