/**
 * Portuguese word list.
 *
 * Leans Brazilian, since Brazil is roughly four fifths of all Portuguese
 * speakers, but keeps European Portuguese references (pastel de nata, bacalhau)
 * in the mix and avoids words that only work on one side of the Atlantic.
 */
export const portugueseWords: string[] = [
  // Comida e bebida
  'Feijoada',
  'Pastel de nata',
  'Coxinha',
  'Brigadeiro',
  'Churrasco',
  'Açaí',
  'Pão de queijo',
  'Bacalhau',
  'Caipirinha',
  'Farofa',
  'Tapioca',
  'Francesinha',
  'Cuscuz',
  'Guaraná',
  'Cafezinho',
  'Salgadinho',
  'Bolo de aniversário',
  'Sorvete',

  // Cultura e festas
  'Carnaval',
  'Samba',
  'Fado',
  'Forró',
  'Festa junina',
  'Roda de capoeira',
  'Bloquinho',
  'Réveillon',
  'Saudade',
  'Novela',
  'Futebol de várzea',
  'Sunga',
  'Chinelo',
  'Rede de dormir',

  // Pessoas
  'Avó',
  'Vizinho fofoqueiro',
  'Porteiro',
  'Dentista',
  'Juiz de futebol',
  'Cabeleireiro',
  'Bombeiro',
  'Salva-vidas',
  'Carteiro',
  'Mágico',
  'Babá',
  'Encanador',
  'Palhaço',
  'Guia turístico',

  // Animais
  'Pinguim',
  'Polvo',
  'Bicho-preguiça',
  'Flamingo',
  'Ouriço',
  'Morcego',
  'Esquilo',
  'Gaivota',
  'Baleia',
  'Borboleta',
  'Formiga',
  'Tucano',
  'Capivara',
  'Jacaré',

  // Lugares
  'Farol',
  'Vulcão',
  'Ilha deserta',
  'Casa mal-assombrada',
  'Laje',
  'Cachoeira',
  'Camping',
  'Museu',
  'Lavanderia',
  'Montanha-russa',
  'Feira',
  'Praia',
  'Deserto',
  'Floresta',
  'Praça',

  // Situações
  'Ressaca',
  'Jet lag',
  'Soluço',
  'Espirro',
  'Ronco',
  'Perder as chaves',
  'Dormir demais',
  'Ficar na fila',
  'Baliza',
  'Embrulhar presente',
  'Encontro às cegas',
  'Entrevista de emprego',
  'Mudança',
  'Exame de direção',
  'Festa surpresa',
  'Elevador quebrado',

  // Sensações
  'Nostalgia',
  'Saudade de casa',
  'Arrepio',
  'Frio na barriga',
  'Queimadura de sol',
  'Perna dormente',
  'Déjà vu',
  'Medo de palco',
  'Ataque de riso',
  'Vontade de doce',

  // Esporte e lazer
  'Futebol',
  'Maratona',
  'Ioga',
  'Caratê',
  'Surfe',
  'Mergulho',
  'Xadrez',
  'Karaokê',
  'Jardinagem',
  'Tricô',
  'Patinação',
  'Dardos',
  'Esconde-esconde',
  'Vôlei de praia',
  'Ciclismo',

  // Tecnologia
  'Selfie',
  'Podcast',
  'Emoji',
  'Senha do wifi',
  'Grupo do WhatsApp',
  'Bateria acabando',
  'Print da tela',
  'Chamada de vídeo',
  'Spam',
  'Modo avião',
  'Código QR',
  'Corretor automático',

  // Clima e natureza
  'Relâmpago',
  'Tornado',
  'Arco-íris',
  'Boneco de neve',
  'Onda de calor',
  'Areia movediça',
  'Lua cheia',
  'Estrela cadente',
  'Poça',
  'Neblina',

  // Coisas
  'Guarda-chuva',
  'Despertador',
  'Mala',
  'Óculos de sol',
  'Chiclete',
  'Controle remoto',
  'Aspirador',
  'Escova de dentes',
  'Cofrinho',
  'Carrinho de mão',
  'Chaleira',
  'Cama elástica',
  'Plástico bolha',
  'Escada',
  'Fogos de artifício',
  'Castelo de areia',
  'Bigode',
  'Tatuagem',
  'Mapa do tesouro',
  'Máquina do tempo',
];
