/**
 * Spanish word list.
 *
 * Written natively rather than translated. Leans on references shared across
 * Spain and Latin America (sobremesa, chancla, piñata) and avoids items that
 * only land in one country.
 */
export const spanishWords: string[] = [
  // Comida y bebida
  'Paella',
  'Tortilla de patatas',
  'Churros',
  'Tapas',
  'Guacamole',
  'Empanada',
  'Arepa',
  'Ceviche',
  'Asado',
  'Chorizo',
  'Flan',
  'Horchata',
  'Sangría',
  'Mate',
  'Tamal',
  'Dulce de leche',
  'Aceitunas',
  'Jamón',

  // Cultura y fiestas
  'Flamenco',
  'Piñata',
  'Sobremesa',
  'Siesta',
  'Quinceañera',
  'Día de Muertos',
  'Carnaval',
  'Mariachi',
  'Reguetón',
  'Telenovela',
  'Nochevieja',
  'Las doce uvas',
  'Feria',
  'Procesión',
  'Salsa',
  'Tango',

  // Personas
  'Abuela',
  'Vecino chismoso',
  'Portero',
  'Dentista',
  'Árbitro',
  'Peluquero',
  'Bombero',
  'Socorrista',
  'Cartero',
  'Mago',
  'Niñera',
  'Fontanero',
  'Payaso',
  'Guía turístico',

  // Animales
  'Pingüino',
  'Pulpo',
  'Perezoso',
  'Flamenco rosa',
  'Erizo',
  'Murciélago',
  'Ardilla',
  'Gaviota',
  'Ballena',
  'Mariposa',
  'Hormiga',
  'Cocodrilo',
  'Llama',
  'Toro',

  // Lugares
  'Faro',
  'Volcán',
  'Isla desierta',
  'Casa embrujada',
  'Azotea',
  'Cascada',
  'Camping',
  'Museo',
  'Lavandería',
  'Montaña rusa',
  'Mercado',
  'Playa',
  'Desierto',
  'Selva',
  'Plaza mayor',

  // Situaciones
  'Resaca',
  'Jet lag',
  'Hipo',
  'Estornudo',
  'Ronquido',
  'Chancla voladora',
  'Perder las llaves',
  'Quedarse dormido',
  'Hacer cola',
  'Aparcar en paralelo',
  'Envolver un regalo',
  'Cita a ciegas',
  'Entrevista de trabajo',
  'Mudanza',
  'Examen de conducir',
  'Fiesta sorpresa',

  // Sensaciones
  'Nostalgia',
  'Morriña',
  'Piel de gallina',
  'Mariposas en el estómago',
  'Quemadura de sol',
  'Pierna dormida',
  'Déjà vu',
  'Miedo escénico',
  'Vergüenza ajena',
  'Antojo',

  // Deporte y ocio
  'Fútbol',
  'Maratón',
  'Yoga',
  'Karate',
  'Surf',
  'Buceo',
  'Ajedrez',
  'Karaoke',
  'Jardinería',
  'Tejer',
  'Patinaje',
  'Dardos',
  'Escondite',
  'Baloncesto',
  'Ciclismo',

  // Tecnología
  'Selfi',
  'Pódcast',
  'Emoji',
  'Contraseña del wifi',
  'Grupo de WhatsApp',
  'Batería baja',
  'Captura de pantalla',
  'Videollamada',
  'Spam',
  'Modo avión',
  'Código QR',
  'Autocorrector',

  // Clima y naturaleza
  'Relámpago',
  'Tornado',
  'Arcoíris',
  'Muñeco de nieve',
  'Ola de calor',
  'Arenas movedizas',
  'Luna llena',
  'Estrella fugaz',
  'Charco',
  'Niebla',

  // Cosas
  'Paraguas',
  'Despertador',
  'Maleta',
  'Gafas de sol',
  'Chicle',
  'Mando a distancia',
  'Aspiradora',
  'Cepillo de dientes',
  'Hucha',
  'Carretilla',
  'Hervidor',
  'Cama elástica',
  'Plástico de burbujas',
  'Escalera',
  'Fuegos artificiales',
  'Castillo de arena',
  'Bigote',
  'Tatuaje',
  'Mapa del tesoro',
  'Máquina del tiempo',
];
